export const browserCoreExamples = [
  "cml-hive-assist browser status",
  "cml-hive-assist browser start",
  "cml-hive-assist browser stop",
  "cml-hive-assist browser tabs",
  "cml-hive-assist browser open https://example.com",
  "cml-hive-assist browser focus abcd1234",
  "cml-hive-assist browser close abcd1234",
  "cml-hive-assist browser screenshot",
  "cml-hive-assist browser screenshot --full-page",
  "cml-hive-assist browser screenshot --ref 12",
  "cml-hive-assist browser snapshot",
  "cml-hive-assist browser snapshot --format aria --limit 200",
  "cml-hive-assist browser snapshot --efficient",
  "cml-hive-assist browser snapshot --labels",
];

export const browserActionExamples = [
  "cml-hive-assist browser navigate https://example.com",
  "cml-hive-assist browser resize 1280 720",
  "cml-hive-assist browser click 12 --double",
  'cml-hive-assist browser type 23 "hello" --submit',
  "cml-hive-assist browser press Enter",
  "cml-hive-assist browser hover 44",
  "cml-hive-assist browser drag 10 11",
  "cml-hive-assist browser select 9 OptionA OptionB",
  "cml-hive-assist browser upload /tmp/file.pdf",
  'cml-hive-assist browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "cml-hive-assist browser dialog --accept",
  'cml-hive-assist browser wait --text "Done"',
  "cml-hive-assist browser evaluate --fn '(el) => el.textContent' --ref 7",
  "cml-hive-assist browser console --level error",
  "cml-hive-assist browser pdf",
];
